### ISSUE TITLE
Add Gradle-Support

### ISSUE THREAD

**Issue by stefanzilske** [red6/dmn-check#2] opened 2020-03-05 12:16 UTC
Hi,

I would love to use your DMN-check tool, alas, I am forced to build with Gradle and the Maven-Plugin is of no use.

Could you not add a Gradle-plugin?

Cheers,
Stefan

**Comment by pSub** [comment] 2020-03-06 12:47
That is a good idea. I've added a Gradle Plugin in PR #3. Could you please take a look if it works for you? This was my first deeper encounter with Gradle, so there might be some rough edges.

**Comment by pSub** [comment] 2020-03-18 14:41
@stefanzilske Do you had a chance testing the PR?

**Comment by stefanzilske** [comment] 2020-03-19 16:03
@pSub sorry, I was not able to build behind my customer's proxy, but I was able to do it from home office today. I needed to adjust your build.gradle a little in order to get plugin id, which I could use to apply the plugin. I added:

```
gradlePlugin {
    plugins {
        simplePlugin {
            id = 'de.redsix.dmncheck'
            implementationClass = 'de.redsix.dmncheck.DmnCheckGradlePlugin'
        }
    }
}
```

When I run the checkDmn task now I get the following Exception, which is probably not directly related to your plugin:

```
Caused by: java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
        at org.apache.xerces.parsers.AbstractDOMParser.startDocument(Unknown Source)
        at org.apache.xerces.impl.xs.XMLSchemaValidator.startDocument(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.startDocument(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentScannerImpl.startEntity(Unknown Source)
        at org.apache.xerces.impl.XMLVersionDetector.startDocumentParsing(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at org.camunda.bpm.model.xml.impl.util.DomUtil.parseInputStream(DomUtil.java:240)
        at org.camunda.bpm.model.xml.impl.parser.AbstractModelParser.parseModelFromStream(AbstractModelParser.java:131)
        at org.camunda.bpm.model.dmn.impl.DmnParser.parseModelFromStream(DmnParser.java:72)
        at org.camunda.bpm.model.dmn.Dmn.doReadModelFromInputStream(Dmn.java:243)
        at org.camunda.bpm.model.dmn.Dmn.doReadModelFromFile(Dmn.java:231)
        at org.camunda.bpm.model.dmn.Dmn.readModelFromFile(Dmn.java:146)
        at de.redsix.dmncheck.plugin.PluginBase.testFile(PluginBase.java:52)
        at de.redsix.dmncheck.plugin.PluginBase.testFiles(PluginBase.java:42)
        at de.redsix.dmncheck.plugin.PluginBase.validate(PluginBase.java:36)
        at de.redsix.dmncheck.DmnCheckTask.validateFiles(DmnCheckTask.java:31)
```

I have had this issue before, when dealing with Camunda, but I could not yet figure our how to solve it in a sustainable manner :(

Right now I have xml-apis pinned to version 1.4.01 since I upgraded to Camunda 7.12.

Maybe you can help me to sort this out.

**Comment by pSub** [comment] 2020-03-20 14:20
Thank you for testing. I will look into the problems you had. In the meantime you can try if the following (very simple) test project works for you. 
[dmn-check-gradle-plugin-test.zip](https://github.com/red6/dmn-check/files/4360018/dmn-check-gradle-plugin-test.zip)

**Comment by pSub** [comment] 2021-03-06 22:02
Hi @stefanzilske, I haven't touched the Gradle plugin since my last comment and I am still unable to reproduce your error. I suspect some classpath problems in your setup. Are you still interested in the Gradle plugin? If so please try it again. You might want to give the example project a try as well.

**Comment by stefanzilske** [comment] 2021-03-16 08:01
Hi @pSub - sorry, I forgot about this to be honest .. but I am in a project right now, where DMN is used as well and will give it another try!

**Comment by pSub** [comment] 2021-04-06 21:23
I did a clean up of the PR (#3) corresponding to this issue. Fixed some stuff and merged `master` into it. I also used the plugin in a random project I found on github which uses Gralde and has some dmn files, see https://github.com/pSub/ia-task-configuration/commit/f40743bacb6707f9720e3a17afed4efb49ebb948. That worked out fine.

Could you get it to work in your project?

**Comment by pSub** [comment] 2021-10-01 12:10
I've release version `1.2.1` of the dmn-check Gradle Plugin. It can be used as

```
plugins {
  id 'de.redsix.dmn-check.gradle-plugin' version '1.2.1'
}
```

I've tested the plugin in the project https://github.com/pSub/ia-task-configuration/ (see 05c06d6be3a855ca2819f562240ccd29252e128f). 

I'm closing this issue now. Please open a new issue if there are further problems with the Gradle plugin.

**Closed by pSub** 2021-10-01 12:10 UTC
Labels: enhancement
